CREATE AGGREGATE jsonb_merge(jsonb) (
    SFUNC = 'jsonb_concat',
    STYPE = jsonb,
    INITCOND = '{}'
);

CREATE TABLE aggregate_elements (
    item_hash VARCHAR NOT NULL,
    key VARCHAR NOT NULL,
    owner VARCHAR NOT NULL,
    content JSONB NOT NULL,
    creation_datetime TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (item_hash)
);
CREATE INDEX ix_key_owner ON aggregate_elements (key, owner);
CREATE INDEX ix_time_desc ON aggregate_elements (creation_datetime DESC);

CREATE TABLE chain_txs (
    hash VARCHAR NOT NULL,
    chain VARCHAR NOT NULL,
    height INTEGER NOT NULL,
    datetime TIMESTAMPTZ NOT NULL,
    publisher VARCHAR NOT NULL,
    protocol VARCHAR NOT NULL,
    protocol_version INTEGER NOT NULL,
    content JSONB NOT NULL,
    PRIMARY KEY (hash)
);

CREATE TABLE chains_sync_status (
    chain VARCHAR NOT NULL,
    height INTEGER NOT NULL,
    last_update TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (chain)
);

CREATE TABLE files (
    hash VARCHAR NOT NULL,
    size BIGINT,
    type VARCHAR NOT NULL,
    PRIMARY KEY (hash)
);

CREATE TABLE file_pins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_hash VARCHAR NOT NULL,
    created TIMESTAMPTZ NOT NULL,
    type VARCHAR NOT NULL,
    tx_hash VARCHAR,
    owner VARCHAR,
    item_hash VARCHAR,
    ref VARCHAR,
    FOREIGN KEY (file_hash) REFERENCES files (hash),
    PRIMARY KEY (id),
    UNIQUE (item_hash)
);

CREATE TABLE forgotten_messages (
    item_hash VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    chain VARCHAR NOT NULL,
    sender VARCHAR NOT NULL,
    signature VARCHAR NOT NULL,
    item_type VARCHAR NOT NULL,
    time TIMESTAMPTZ NOT NULL,
    channel VARCHAR,
    forgotten_by VARCHAR[] NOT NULL,
    PRIMARY KEY (item_hash)
);
CREATE INDEX ix_forgotten_messages_channel ON forgotten_messages (channel);
CREATE INDEX ix_forgotten_messages_sender ON forgotten_messages (sender);
CREATE INDEX ix_forgotten_messages_time ON forgotten_messages (time);

CREATE TABLE message_status (
    item_hash VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    reception_time TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (item_hash)
);

CREATE TABLE messages (
    item_hash VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    chain VARCHAR NOT NULL,
    sender VARCHAR NOT NULL,
    signature VARCHAR NOT NULL,
    item_type VARCHAR NOT NULL,
    item_content VARCHAR,
    content JSONB NOT NULL,
    time TIMESTAMPTZ NOT NULL,
    channel VARCHAR,
    size INTEGER NOT NULL,
    PRIMARY KEY (item_hash)
);
CREATE INDEX ix_messages_channel ON messages (channel);
CREATE INDEX ix_messages_sender ON messages (sender);
CREATE INDEX ix_messages_time ON messages (time);

CREATE TABLE peers (
    peer_id VARCHAR NOT NULL,
    peer_type VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    source VARCHAR NOT NULL,
    last_seen TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (peer_id, peer_type)
);

CREATE TABLE posts (
    item_hash VARCHAR NOT NULL,
    owner VARCHAR NOT NULL,
    type VARCHAR,
    ref VARCHAR,
    amends VARCHAR,
    channel VARCHAR,
    content JSONB NOT NULL,
    creation_datetime TIMESTAMPTZ NOT NULL,
    latest_amend VARCHAR,
    FOREIGN KEY (amends) REFERENCES posts (item_hash),
    PRIMARY KEY (item_hash)
);
CREATE INDEX ix_posts_amends ON posts (amends);
CREATE INDEX ix_posts_owner ON posts (owner);
CREATE INDEX ix_posts_type ON posts (type);

CREATE TABLE rejected_messages (
    item_hash VARCHAR NOT NULL,
    message JSONB NOT NULL,
    reason VARCHAR NOT NULL,
    traceback VARCHAR,
    PRIMARY KEY (item_hash)
);

CREATE TABLE aggregates (
    key VARCHAR NOT NULL,
    owner VARCHAR NOT NULL,
    content JSONB NOT NULL,
    creation_datetime TIMESTAMPTZ NOT NULL,
    last_revision_hash VARCHAR NOT NULL,
    dirty BOOLEAN NOT NULL,
    FOREIGN KEY (last_revision_hash) REFERENCES aggregate_elements (item_hash),
    PRIMARY KEY (key, owner)
);
CREATE INDEX ix_aggregates_owner ON aggregates (owner);

CREATE TABLE file_tags (
    tag VARCHAR NOT NULL,
    owner VARCHAR NOT NULL,
    file_hash VARCHAR NOT NULL,
    last_updated TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (file_hash) REFERENCES files (hash),
    PRIMARY KEY (tag)
);
CREATE INDEX ix_file_tags_file_hash ON file_tags (file_hash);

CREATE TABLE message_confirmations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_hash VARCHAR NOT NULL,
    tx_hash VARCHAR NOT NULL,
    FOREIGN KEY (item_hash) REFERENCES messages (item_hash),
    FOREIGN KEY (tx_hash) REFERENCES chain_txs (hash) ON DELETE CASCADE,
    PRIMARY KEY (id),
    UNIQUE (item_hash, tx_hash)
);
CREATE INDEX ix_message_confirmations_item_hash ON message_confirmations (item_hash);

CREATE TABLE pending_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_hash VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    chain VARCHAR NOT NULL,
    sender VARCHAR NOT NULL,
    signature VARCHAR NOT NULL,
    item_type VARCHAR NOT NULL,
    item_content VARCHAR,
    content JSONB,
    time TIMESTAMPTZ NOT NULL,
    channel VARCHAR,
    reception_time TIMESTAMPTZ NOT NULL,
    check_message BOOLEAN NOT NULL,
    retries INTEGER NOT NULL,
    tx_hash VARCHAR,
    fetched BOOLEAN NOT NULL,
    FOREIGN KEY (tx_hash) REFERENCES chain_txs (hash),
    PRIMARY KEY (id)
);
CREATE INDEX ix_retries_time ON pending_messages (retries ASC, time ASC);

CREATE TABLE pending_txs (
    tx_hash VARCHAR NOT NULL,
    FOREIGN KEY (tx_hash) REFERENCES chain_txs (hash),
    PRIMARY KEY (tx_hash)
);
