-- Add IDENTITY to tables whose `id` column was migrated as NOT NULL without a
-- sequence/default. In SQLAlchemy these columns were `BigInteger primary_key=True`,
-- which under PostgreSQL produces a `BIGSERIAL` automatically. The raw-SQL port
-- of the Alembic initial migration omitted that, so inserts that didn't supply
-- an explicit `id` failed with "null value in column id".
--
-- This migration is idempotent at the column-default level: it attaches an
-- IDENTITY sequence to each affected `id` column. Existing rows retain their
-- ids; future inserts that omit the column are auto-numbered.
--
-- Tables affected:
--   - balances
--   - account_costs
--   - vm_machine_volumes
--
-- file_pins / pending_messages / message_confirmations were already fixed in
-- V0001.

ALTER TABLE balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('balances', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM balances), 0), 1)
);

ALTER TABLE account_costs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('account_costs', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM account_costs), 0), 1)
);

ALTER TABLE vm_machine_volumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('vm_machine_volumes', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM vm_machine_volumes), 0), 1)
);
