-- Persist node scoring metrics in range-partitioned tables.
--
-- Port of pyaleph alembic migration
-- 0059_b9c4f1e6a2d7_persist_node_metrics.py (#1150).
--
-- Creates crn_metrics and ccn_metrics as RANGE-partitioned tables on
-- measured_at (TIMESTAMPTZ), with monthly child partitions, a DEFAULT
-- catch-all partition, and a 12-month retention horizon at backfill.
-- Backfills from the existing JSON-unnesting views (filtered to the
-- retention window), then drops the views. Seeds a cron job that
-- maintains partitions (creates next month, drops past-cutoff).
--
-- Partition design:
--  * Partition key: measured_at TIMESTAMPTZ
--  * Granularity: 1 month
--  * Initial coverage: [now - 12 months, now + 2 months) (13 child
--    partitions: 12 retention months + current + 1 lookahead month)
--  * Plus a DEFAULT partition as a safety net for out-of-range timestamps
--  * PK is (id, measured_at) because Postgres requires the partition key
--    in any PK on a partitioned table; id stays an IDENTITY column
--  * Indexes: ix_*_item_hash, ix_*_node_id_measured_at (built on the
--    parent, replicated to children via the partitioned-index mechanism)
--  * FK to messages(item_hash) ON DELETE CASCADE, added after backfill.

-- 1. Create both parent tables (PARTITION BY RANGE on measured_at).
CREATE TABLE crn_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    measured_at TIMESTAMPTZ NOT NULL,
    item_hash TEXT NOT NULL,
    node_id TEXT NOT NULL,
    base_latency DOUBLE PRECISION,
    base_latency_ipv4 DOUBLE PRECISION,
    full_check_latency DOUBLE PRECISION,
    diagnostic_vm_latency DOUBLE PRECISION,
    PRIMARY KEY (id, measured_at)
) PARTITION BY RANGE (measured_at);

CREATE TABLE ccn_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    measured_at TIMESTAMPTZ NOT NULL,
    item_hash TEXT NOT NULL,
    node_id TEXT NOT NULL,
    base_latency DOUBLE PRECISION,
    base_latency_ipv4 DOUBLE PRECISION,
    metrics_latency DOUBLE PRECISION,
    aggregate_latency DOUBLE PRECISION,
    file_download_latency DOUBLE PRECISION,
    pending_messages INTEGER,
    eth_height_remaining INTEGER,
    PRIMARY KEY (id, measured_at)
) PARTITION BY RANGE (measured_at);

-- 2. Create monthly child partitions for [now - 12 months, now + 2 months)
--    plus a DEFAULT catch-all on each parent. Done dynamically in a
--    PL/pgSQL block since the bounds depend on migration-time "now".
DO $$
DECLARE
    retention_months CONSTANT INT := 12;
    lookahead_months CONSTANT INT := 1;
    tbl TEXT;
    now_month TIMESTAMPTZ := date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC';
    lower_bound TIMESTAMPTZ;
    upper_bound TIMESTAMPTZ;
    cursor_month TIMESTAMPTZ;
    end_exclusive TIMESTAMPTZ;
    part_name TEXT;
BEGIN
    cursor_month := now_month - make_interval(months => retention_months);
    end_exclusive := now_month + make_interval(months => lookahead_months + 1);

    FOREACH tbl IN ARRAY ARRAY['crn_metrics', 'ccn_metrics'] LOOP
        lower_bound := cursor_month;
        WHILE lower_bound < end_exclusive LOOP
            upper_bound := lower_bound + make_interval(months => 1);
            -- Name partitions in UTC so they match the maintenance cron
            -- (toolkit::partitions::partition_name formats the UTC month).
            -- to_char renders a timestamptz in the session timezone, so a
            -- non-UTC session would otherwise name a UTC-boundary partition
            -- under the wrong month and the cron's UTC-named CREATE would
            -- overlap and fail.
            part_name := tbl || '_' || to_char(lower_bound AT TIME ZONE 'UTC', 'YYYY_MM');
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                part_name, tbl, lower_bound, upper_bound
            );
            lower_bound := upper_bound;
        END LOOP;
        -- DEFAULT partition: catch-all for timestamps outside the rolling
        -- range (e.g. far-future scoring posts). The cron job alerts if
        -- this ever holds rows; data here is hard to migrate to a proper
        -- partition without DETACH + INSERT, so it should stay empty in
        -- steady state.
        EXECUTE format('CREATE TABLE %I PARTITION OF %I DEFAULT', tbl || '_default', tbl);
    END LOOP;
END $$;

-- 3. Backfill from the existing views, filtered to the retention window.
--    Cast the float epoch to TIMESTAMPTZ so partition routing picks the
--    right child.
INSERT INTO crn_metrics (
    item_hash, measured_at, node_id, base_latency, base_latency_ipv4,
    full_check_latency, diagnostic_vm_latency
)
SELECT
    item_hash,
    to_timestamp(measured_at) AS measured_at,
    node_id, base_latency, base_latency_ipv4,
    full_check_latency, diagnostic_vm_latency
FROM crn_metric_view
WHERE node_id IS NOT NULL
  AND measured_at IS NOT NULL
  AND to_timestamp(measured_at) >= (date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC') - INTERVAL '12 months';

INSERT INTO ccn_metrics (
    item_hash, measured_at, node_id, base_latency, base_latency_ipv4,
    metrics_latency, aggregate_latency, file_download_latency,
    pending_messages, eth_height_remaining
)
SELECT
    item_hash,
    to_timestamp(measured_at) AS measured_at,
    node_id, base_latency, base_latency_ipv4,
    metrics_latency, aggregate_latency, file_download_latency,
    pending_messages, eth_height_remaining
FROM ccn_metric_view
WHERE node_id IS NOT NULL
  AND measured_at IS NOT NULL
  AND to_timestamp(measured_at) >= (date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC') - INTERVAL '12 months';

-- 4. Build indexes on the parent (partitioned-index, cascades to children).
CREATE INDEX ix_crn_metrics_item_hash ON crn_metrics (item_hash);
CREATE INDEX ix_crn_metrics_node_id_measured_at ON crn_metrics (node_id, measured_at DESC);
CREATE INDEX ix_ccn_metrics_item_hash ON ccn_metrics (item_hash);
CREATE INDEX ix_ccn_metrics_node_id_measured_at ON ccn_metrics (node_id, measured_at DESC);

-- 5. FK to messages. PG does not support NOT VALID on partitioned tables
--    (yet, as of PG 17). The ADD CONSTRAINT validates each child partition
--    in one pass -- still faster than the per-INSERT FK check we'd pay if
--    the constraint were present during step 3.
ALTER TABLE crn_metrics
    ADD CONSTRAINT fk_crn_metrics_item_hash
    FOREIGN KEY (item_hash) REFERENCES messages(item_hash) ON DELETE CASCADE;
ALTER TABLE ccn_metrics
    ADD CONSTRAINT fk_ccn_metrics_item_hash
    FOREIGN KEY (item_hash) REFERENCES messages(item_hash) ON DELETE CASCADE;

DROP VIEW IF EXISTS crn_metric_view;
DROP VIEW IF EXISTS ccn_metric_view;

-- 6. Seed the cron-job row that drives partition maintenance. Daily
--    interval. last_run set to epoch so the first scheduler tick runs the
--    job (creates next month if missing, drops anything past retention).
INSERT INTO cron_jobs(id, interval, last_run)
VALUES ('metrics_partition', 86400, '1970-01-01 00:00:00+00');
