//! Golden-CID integration tests for `folder_hash::hash_folder_root`.
//!
//! Each test builds a deterministic folder structure on disk, runs the local
//! hasher, and asserts the result equals a golden CID generated from real kubo
//! via `tests/regen-folder-hash-goldens.sh`.
//!
//! The fixture-builder functions below mirror the bash fixtures in the regen
//! script — keep them in sync.
//!
//! All tests are `#[ignore]`d until Task 9 fills in real goldens.

use aleph_sdk::ipfs::{CidVersion, UploadFolderOptions, collect_folder_files};
use std::fs;
use std::io::Write;
use std::path::Path;
use tempfile::TempDir;

// === Fixtures ===

fn fixture_single_file_small(root: &Path) {
    fs::write(root.join("hello.txt"), b"hello\n").unwrap();
}

fn fixture_single_file_multi_chunk(root: &Path) {
    // The bash regen script uses `tr '\0' '\xab'` which GNU tr interprets as
    // the literal character 'x' (0x78), not hex 0xAB.  Match that behaviour.
    let mut f = fs::File::create(root.join("big.bin")).unwrap();
    let chunk = vec![b'x'; 1024];
    for _ in 0..1024 {
        f.write_all(&chunk).unwrap();
    }
}

fn fixture_flat_dir_small(root: &Path) {
    for c in 'a'..='j' {
        fs::write(root.join(format!("{c}.txt")), [c as u8]).unwrap();
    }
}

fn fixture_nested_dir(root: &Path) {
    fs::write(root.join("top.txt"), b"top\n").unwrap();
    let sub = root.join("sub");
    fs::create_dir(&sub).unwrap();
    fs::write(sub.join("inner.txt"), b"inner\n").unwrap();
    let deeper = sub.join("deeper");
    fs::create_dir(&deeper).unwrap();
    fs::write(deeper.join("leaf.txt"), b"leaf\n").unwrap();
}

fn fixture_hamt_short_names(root: &Path) {
    // 6000 files * (8-char name + 36-byte CIDv1) = 264000 > 262144 (HAMT threshold)
    for i in 0..6000u32 {
        fs::write(root.join(format!("{i:08}")), b"x").unwrap();
    }
}

fn fixture_hamt_long_names(root: &Path) {
    // 920 files * (250-char name + 36-byte CIDv1) = 263120 > 262144 (HAMT threshold).
    // Names are 4-digit prefix + 246-char suffix to stay within the Linux
    // 255-char filename limit while still triggering HAMT sharding.
    let suffix = "z".repeat(246);
    for i in 0..920u32 {
        fs::write(root.join(format!("{i:04}{suffix}")), b"x").unwrap();
    }
}

fn fixture_hamt_multi_level(root: &Path) {
    // The collision pair is discovered by the find_hamt_collision example in Task 9.
    // Until then, both files are empty and this fixture won't be exercised
    // (test is #[ignore]'d).
    let collision_a = include_str!("hamt_collision_a.txt").trim();
    let collision_b = include_str!("hamt_collision_b.txt").trim();
    if !collision_a.is_empty() && !collision_b.is_empty() {
        fs::write(root.join(collision_a), b"a").unwrap();
        fs::write(root.join(collision_b), b"b").unwrap();
    }
    fs::write(root.join("Z"), b"c").unwrap();
}

// === Helper: run the hasher over a built fixture ===

fn hash_root(root: &Path, version: CidVersion) -> String {
    let entries = collect_folder_files(root, true).unwrap();
    let mut opts = UploadFolderOptions::default();
    opts.cid_version = version;
    aleph_sdk::__test_only_hash_folder_root(&entries, &opts)
        .expect("hashing must succeed")
        .to_string()
}

// === Goldens ===
//
// Generated by tests/regen-folder-hash-goldens.sh against kubo v0.30.0.
// Regenerate after any change to folder_hash.rs that could affect output bytes.

const GOLDEN_SINGLE_FILE_SMALL_V1: &str =
    "bafybeigdcg7pksx2zk5336vrfsktjodlr4rbfz37qr3koc5xboxe5ekv24";
const GOLDEN_SINGLE_FILE_MULTI_CHUNK_V1: &str =
    "bafybeiconxawjaqtqwur53yryub7awouqco4rlqqfbv6jypyfzeewmhrbe";
const GOLDEN_FLAT_DIR_SMALL_V1: &str =
    "bafybeic44rqkymydh3gvookwnqasv5ydbk5owkl7l2pkvgmh4stny4cdly";
const GOLDEN_NESTED_DIR_V1: &str = "bafybeidcclyz24mrl4furbaf4ecb3ks52dbfer7r6dxqavd4wrqg7bp7lu";
const GOLDEN_HAMT_SHORT_NAMES_V1: &str =
    "bafybeidk3a4hr6msgcv24pkutwrethttydqzx56m724lsg75fzgeu3yzn4";
const GOLDEN_HAMT_LONG_NAMES_V1: &str =
    "bafybeidurl753n2ka5wvgx6qyifmilikuh2lb5eucgdpo3pu253pkx7r4e";
const GOLDEN_HAMT_MULTI_LEVEL_V1: &str =
    "bafybeiegiotpslrdicvq2duzx4gmigbxyocs7fw37q7hmwa3sseiz2tj7y";
const GOLDEN_FLAT_DIR_SMALL_V0: &str = "QmaVbVDQrEVXH6EAQQExN82Xt44VmrQWkkey4S8eYcTNRs";

#[test]

fn golden_single_file_small_v1() {
    let dir = TempDir::new().unwrap();
    fixture_single_file_small(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V1),
        GOLDEN_SINGLE_FILE_SMALL_V1
    );
}

#[test]

fn golden_single_file_multi_chunk_v1() {
    let dir = TempDir::new().unwrap();
    fixture_single_file_multi_chunk(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V1),
        GOLDEN_SINGLE_FILE_MULTI_CHUNK_V1
    );
}

#[test]

fn golden_flat_dir_small_v1() {
    let dir = TempDir::new().unwrap();
    fixture_flat_dir_small(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V1),
        GOLDEN_FLAT_DIR_SMALL_V1
    );
}

#[test]

fn golden_nested_dir_v1() {
    let dir = TempDir::new().unwrap();
    fixture_nested_dir(dir.path());
    assert_eq!(hash_root(dir.path(), CidVersion::V1), GOLDEN_NESTED_DIR_V1);
}

#[test]

fn golden_hamt_short_names_v1() {
    let dir = TempDir::new().unwrap();
    fixture_hamt_short_names(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V1),
        GOLDEN_HAMT_SHORT_NAMES_V1
    );
}

#[test]

fn golden_hamt_long_names_v1() {
    let dir = TempDir::new().unwrap();
    fixture_hamt_long_names(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V1),
        GOLDEN_HAMT_LONG_NAMES_V1
    );
}

#[test]

fn golden_hamt_multi_level_v1() {
    let dir = TempDir::new().unwrap();
    fixture_hamt_multi_level(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V1),
        GOLDEN_HAMT_MULTI_LEVEL_V1
    );
}

#[test]

fn golden_flat_dir_small_v0() {
    let dir = TempDir::new().unwrap();
    fixture_flat_dir_small(dir.path());
    assert_eq!(
        hash_root(dir.path(), CidVersion::V0),
        GOLDEN_FLAT_DIR_SMALL_V0
    );
}
