#!/usr/bin/env bash
# Regenerate prost Rust code from .proto files. Requires protoc.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

proto_dir="$PWD/crates/aleph-sdk/proto"

# Build a small throwaway Cargo project that runs prost-build
mkdir -p "$tmp/src"
cat > "$tmp/Cargo.toml" <<'EOF'
[package]
name = "gen-proto"
version = "0.0.0"
edition = "2021"
[dependencies]
prost-build = "0.13"
EOF
cat > "$tmp/src/main.rs" <<EOF
fn main() {
    let out = std::env::args().nth(1).expect("usage: gen-proto <out-dir>");
    prost_build::Config::new()
        .out_dir(&out)
        .compile_protos(
            &["merkledag.proto", "unixfs.proto"],
            &["$proto_dir"],
        )
        .expect("prost compile failed");
}
EOF

gen_out=$(mktemp -d)
cargo run --quiet --manifest-path "$tmp/Cargo.toml" -- "$gen_out"

for proto in merkledag unixfs; do
    {
        echo "// @generated by prost-build from crates/aleph-sdk/proto/${proto}.proto"
        echo "// Do not edit manually. Regenerate with: just generate-proto"
        cat "$gen_out/${proto}.rs"
    } > "crates/aleph-sdk/src/proto/${proto}.rs"
done

rm -rf "$gen_out"
echo "Proto files regenerated."
