// @generated by prost-build from crates/aleph-sdk/proto/merkledag.proto
// Do not edit manually. Regenerate with: just generate-proto
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbLink {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "3")]
    pub tsize: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbNode {
    #[prost(message, repeated, tag = "2")]
    pub links: ::prost::alloc::vec::Vec<PbLink>,
    #[prost(bytes = "vec", optional, tag = "1")]
    pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
